name: Bandit SAST Scan

on:
  push:

jobs:
  sast:
    runs-on: ubuntu-latest
    name: Run Bandit

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit and Save Report
        run: |
          bandit -ll -ii -r . -f json -o bandit-report.json

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit-report.json
